lakefile.lean

Rebuild example JSON at the right times. We previously depended on the dependencies of our modules, rather than the modules themselves.

fix: highlighting facet dependencies

---

.github/workflows/ci.yml
lakefile.lean
src/compat/SubVerso/Compat.lean
src/examples/SubVerso/Examples.lean
src/highlighting/SubVerso/Highlighting/Code.lean

To work with newer Lean versions, SubVerso needs to have some compatibility shims.

feat: add compatilibity shim system

---

src/highlighting/SubVerso/Highlighting/Code.lean
src/highlighting/SubVerso/Highlighting/Highlighted.lean

This is the SubVerso side of fixing #10.

feat: bundle messages that co-occur

---

src/examples/SubVerso/Examples.lean

Instead of trying to find the location of `elan`-disguised-as-`lake`, this now invokes `elan`
plainly, using `elan run --install <toolchain>`.
This fixes building a  multi-toolchain verso project on my setup (where `elan` comes from nix, but it should not matter where `elan` comes from, only that the `lake` in path is from elan). 
Fixes #4

fix: invoke elan explicitly

---

src/compat/SubVerso/Compat.lean
src/examples/SubVerso/Examples/Slice.lean
src/examples/SubVerso/Examples/Slice/Attribute.lean

Make syntax slicing extensible so that custom slicers can be written for various productions that aren't handled well by the default heuristics.

feat: extensible slicing

---

demo/Demo.lean
src/examples/SubVerso/Examples.lean

This makes it easier to just refer to a name in the text.

feat: SubVerso support for using a name as an example

---

src/examples/SubVerso/Examples.lean

This allows downstream clients to implement their own signature checking facilities.

feat: factor out the signature processor as a helper

---

InternalTests.lean
Tests.lean
demo-toml/Demo.lean
demo/Demo.lean
src/examples/SubVerso/Examples.lean

Examples with linter warnings weren't being extracted, because the linters were run after the example extraction process. Linters are now run redundantly to work around this.

fix: missing warnings from some examples

---

src/highlighting/SubVerso/Highlighting/Code.lean

This fixes a few missing highlights, but the highlight system really needs to have expression granularity rather than token granularity.

feat: highlight more pretty-printer output

---

src/compat/SubVerso/Compat.lean
src/highlighting/SubVerso/Highlighting/Code.lean
src/highlighting/SubVerso/Highlighting/Highlighted.lean

This is preparatory work for getting the examples in Markdown docstrings to render properly.

feat: save definition sites in code examples

---

.github/workflows/ci.yml
ExtractModule.lean
lakefile.lean
src/compat/SubVerso/Compat.lean

Adds the ability to highlight a whole module.

feat: source file highlighting

---

.github/workflows/ci.yml
src/compat/SubVerso/Compat.lean
src/examples/SubVerso/Examples.lean

Async elaboration of theorems means that proof states are not necessarily available in the info tree when command elaboration returns. It needs to be disabled for highlighted code, so that it's working with complete information.

chore: bump for 2025-03-16

---

Extract.lean
ExtractModule.lean

Prior to this change, `subverso-extract` and `subverso-extract-mod` would fail on any module that imports a non-core module with `initialize` declarations.

fix: enable initialisers in Extract[Module]

---

lakefile.lean

This is to work around a compilation issue that appeared in downstream projects as of nightly-2025-03-30

chore: temporarily disable precompiled modules

---

ExtractModule.lean
InternalTests.lean
src/SubVerso/Compat.lean
src/SubVerso/Highlighting/Code.lean

Also updates the output format of subverso-extract-mod to be split by declaration.

perf: spend less time looking for proof states

---

InternalTests.lean
src/SubVerso/Compat.lean
src/SubVerso/Examples.lean
src/SubVerso/Examples/Messages.lean
src/SubVerso/Examples/Messages/NormalizeLineNum.lean
src/SubVerso/Examples/Messages/NormalizeMetavars.lean

Versions of these functions ended up existing in various versions in a variety of clients of SubVerso. Better to upstream them once and for all.

feat: message normalization

---

src/SubVerso/Compat.lean
src/SubVerso/Highlighting/Code.lean
src/SubVerso/Highlighting/Messages.lean

This allows them to be downgraded to warnings while interacting with example files, while still rendering them reliably as errors later.

feat: tag messages as having originally been errors

---

Tests.lean
src/SubVerso/Examples.lean

This stops Lake from using the wrong one in trace files.

fix: delete the LEAN_GITHASH environment variable from subprocesses

---

src/SubVerso/Highlighting/Code.lean

This places the goal highlighting for conv => and match alts on the entire start, rather than just the arrow.

feat: highlight span for conv => and match alts in tactics

---

InternalTests.lean
src/SubVerso/Compat.lean
src/SubVerso/Highlighting/Anchors.lean
src/SubVerso/Highlighting/Code.lean
src/SubVerso/Highlighting/Highlighted.lean
src/SubVerso/Highlighting/Split.lean
src/SubVerso/Highlighting/String.lean

This PR adds a `highlightIncludingUnparsed` method to the `Highlighting` module, which will insert unparsed syntax regions into the output `Highlighted` value. Unparsed regions are determined using the positions on the input syntax and are filled in using the file map. This is useful for demonstrating parsing errors alongside elaboration errors in a single code block.

feat: add highlighting mode that includes unparsed syntax
